### ISSUE TITLE
[Question] how to use this with ngxs emitter plugin ?

### ISSUE THREAD

**Issue by ceyhunn** [ngxs-labs/actions-executing#1]

**Comment by joaqcid** [comment]
i havent used emitter, and i dont know if it leverages the action stream internally, @splincode does the emitter plugin uses actions?

**Comment by splincode** [comment]
```ts
@State<number>({
    name: 'counter',
    defaults: 0
})
export class CounterState {
    @Receiver({ type: '[Counter] Increment value' })
    public static increment({ setState, getState }: StateContext<number>) {
        setState(getState() + 1);
    }
}
```

```ts
export class SingleComponent {
  @Select(actionsExecuting([ { type: '[Counter] Increment value' } ])) 
   myIncrementIsExecuting$: Observable<ActionsExecuting>;
}
```

Do not recommend using this plugin for sync operation. Because it's overhead.

Best cases

```ts
@State<Book[]>({
  name: 'books',
  defaults: []
})
export class BooksState {
  constructor(private api: ApiService) {}

  @Action(AddBook)
  add(ctx: StateContext<Book[]>) {
    return this.api.addBook().pipe(
      tap((book: Book) => {
        ctx.setState((state: Book[]) => state.concat(book));
      })
    );
  }
}
```

```ts
import { actionsExecuting, ActionsExecuting } from '@ngxs-labs/actions-executing';

@Component({
  selector: 'app',
  template: `
    <button [disabled]="addBookIsExecuting$ | async" (click)="addBook()">
      Add book
    </button>

    <span *ngIf="addBookIsExecuting$ | async">
      Loading...
    </span>
  `
})
export class AppComponent {
  @Select(actionsExecuting([AddBook]))
  addBookIsExecuting$: Observable<ActionsExecuting>;

  constructor(private store: Store) {}

  addBook() {
    this.store.dispatch(new AddBook());
  }
}
```

**Comment by ceyhunn** [comment]
Thank you very much for an example..

> Do not recommend using this plugin for sync operation. Because it's overhead.

You mean it is ok for only async call?

**Comment by splincode** [comment]
> it is ok for only async call?

Yes

**Comment by ceyhunn** [comment]
Hi @splincode , Can I use action-executing with dispatcher decorator plugin?

**Comment by splincode** [comment]
@ceyhunn Not sure
What do you think about new plugin:
https://github.com/ngxs-labs/data

**Comment by joaqcid** [comment]
@ceyhunn you can use actions-executing with dispatcher plugin, in fact in. my project im using both actions-executing and dispatcher!

**Comment by ceyhunn** [comment]
Hi @joaqcid , How do you use? Can you give an example?

**Comment by joaqcid** [comment]
@ceyhunn check this post  https://dev.to/joaqcid/ngxs-loading-spinners-and-actions-executing-kla

you can then set the click handler to be like this:

```
@Dispatch()
click = ()=> new MyAction()
```

**Comment by ceyhunn** [comment]
@joaqcid , I don't use action (See [emitter plugin](https://github.com/ngxs-labs/emitter) ).

**Comment by joaqcid** [comment]
oh i thought you said dispatcher, 

no, i dont know if emitter plugin is compatible, if emitter internally uses actions, should work, did you you try it?
