### ISSUE TITLE
Error when fullTemplateTypeCheck is true

### ISSUE THREAD

**Issue by kondelik** [ngxs-labs/actions-executing#10]
Because `actionsExecuting([MyAction])` is returning observable of type `ActionsExecuting` i cant compile my angular project:

```
error TS2322: Type '{ [action: string]: number; }' is not assignable to type 'boolean'.  
```

The reason is that i have enabled `fullTemplateTypeCheck` in my tsconfig.json:

```json
"angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
},
```
I dont want to turn it off, i am beginner with TypeScript / angular and this save my skin multiple times already 🥰 

Better solution should be to have something like `actionsExecutingAsBoolean([MyAction]): Observable<boolean>();` or  `anyActionExecuting([MyAction]): Observable<boolean>();` or something like that (i dont think i care which action is currently executing). But i have no idea how to write it...

------------------------------------------------

**Workaround** is to omit the select type:

```TypeScript
@Select(actionsExecuting([MyAction])) myActionIsExecuting$; //: Observable<ActionsExecuting>;
```
or setting it to any:

```TypeScript
@Select(actionsExecuting([MyAction])) myActionIsExecuting$: any; //: Observable<ActionsExecuting>;
```

**Workaround 2** is to use a pipe:

```TypeScript
import { Pipe, PipeTransform } from '@angular/core';
import { ActionsExecuting } from '@ngxs-labs/actions-executing';

@Pipe({
  name: 'isExecuting'
})
export class IsExecutingPipe implements PipeTransform {

  transform(value: ActionsExecuting, args?: any): boolean {
    return value ? true : false;
  }

  /* Hack to "any"
  transform(value: ActionsExecuting, args?: any): any {
     return value;
  }
  */
}
```
and then chain it with `async`: `[loading]="myActionIsExecuting$ | async | isExecuting"`

**Possible workaround 3**
Is there a way to pipe `@Select`? 😃

**Comment by joaqcid** [comment]
Hi @splite !

Thanks for submitting the issue, 

As you mention above you pretty much have listed all the possible workarounds.

In my opinion i would go with omitting with type, or casting it as Observable<any>

You could `pipe` select doing

` this.store.select(actionsExecuting([actions])).pipe(map(ae=> !!ae)) `

assuming you injected the store

Anyways, i'll take a look and see if we can provide a better solution for this

Stay tuned!

Thanks!

**Comment by joaqcid** [comment]
@splite update to 0.1.3, `hasActionsExecuting` was added to return boolean
