### ISSUE TITLE
Not working with Lazy loaded stores

### ISSUE THREAD

**Issue by luchian94** [ngxs-labs/actions-executing#14]
I tried to use this plugin in an application where I have some modules with stores being lazy loaded and it doesn't seem to work.

Tried playing a bit and importing NgxsActionsExecutingModule into feature module instead of app.module seems to work, but I need to import it multiple modules to work so it needs .forChild or something.

Tried debugging a bit and it seems that ngxsOnInit not being triggered when I import `NgxsActionsExecutingModule.forRoot()` into `app.module`.

Update: the issue was that I had `NgxsModule.forRoot([])` with empty states because my other states were being loaded lazy. This caused ngxsOnInit to not trigger, when I added one initial state into forRoot it started working again.

**Comment by joaqcid** [comment]
Update: the issue was that I had NgxsModule.forRoot([]) with empty states because my other states were being loaded lazy. This caused ngxsOnInit to not trigger, when I added one initial state into forRoot it started working again.
