### ISSUE TITLE
export ActionsExecutingState state

### ISSUE THREAD

**Issue by neverlose-lv** [ngxs-labs/actions-executing#18]
Hi there. In certain scenario `ActionsExecutingState` states values are not working as intended. The state keeps the keys with value = `1`, even when the actions are completed.

Can you add an export of the `ActionsExecutingState`, so I could reset the state (using `StateReset()` method from `ngxs-reset-plugin` https://www.npmjs.com/package/ngxs-reset-plugin) ?

**Comment by joaqcid** [comment]
hi @neverlose-lv can you use the string name of the state? `ngxs_actions_executing` and `ngxs_actions_executed`
