### ISSUE TITLE
Support angular 19

### ISSUE THREAD

**Issue by anschm** [ngxs-labs/actions-executing#23]
We would like to migrate to angular 19. But we are getting dependency issues because this library is not supporting angular 19.

**Comment by joaqcid** [comment]
what version of `@ngxs-labs/actions-executing`  and `@ngxs/store` are you using? 
`@ngxs-labs/actions-executing` should not generate dependency issues with angular 

```
"name": "@ngxs-labs/actions-executing",
...
"peerDependencies": {
    "@ngxs/store": ">=4.0.0 <19.0.0"
},
```

**Comment by markwhitfeld** [comment]
@joaqcid `@ngxs/store` v19 would fail the check.

**Comment by joaqcid** [comment]
@anschm please update to v19 of actions-executing to fix the isse
