### ISSUE TITLE
@Injectable warning with Angular 9

### ISSUE THREAD

**Issue by jfai** [ngxs-labs/actions-executing#3]
Using `actions-executing` with Angular 9 causes this warning during runtime:

`WARN: ''ActionsExecutingState' class should be decorated with @Injectable() right after the @State() decorator'`

**Comment by joaqcid** [comment]
@jfai please update to 0.0.7 and let me know if works

**Comment by jfai** [comment]
Warning is gone in 0.0.7. Much appreciated!
